export const fallbackCollections = [
  {
    id: 1,
    slug: "african-soul",
    name: "African Soul",
    subtitle: "Heritage, roots and contemporary African presence",
    description: "Earth-toned contemporary artwork shaped by memory, rhythm and place.",
    coverImage: "https://images.pexels.com/photos/34017793/pexels-photo-34017793.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    featured: true,
    displayOrder: 1,
    createdAt: new Date(),
  },
  {
    id: 2,
    slug: "form",
    name: "Form",
    subtitle: "Geometry, structure and sculptural balance",
    description: "Architectural compositions for considered contemporary spaces.",
    coverImage: "https://images.pexels.com/photos/1582547/pexels-photo-1582547.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    featured: true,
    displayOrder: 2,
    createdAt: new Date(),
  },
  {
    id: 3,
    slug: "still",
    name: "Still",
    subtitle: "Quiet monochromes and softer interiors",
    description: "Calm pieces for bedrooms, studies and reflective rooms.",
    coverImage: "https://images.pexels.com/photos/8251476/pexels-photo-8251476.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    featured: true,
    displayOrder: 3,
    createdAt: new Date(),
  },
  {
    id: 4,
    slug: "custom",
    name: "Custom",
    subtitle: "Commissioned art for meaningful spaces",
    description: "Bespoke artwork for homes, offices, hospitality and gifting.",
    coverImage: "https://images.pexels.com/photos/29532559/pexels-photo-29532559.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    featured: true,
    displayOrder: 4,
    createdAt: new Date(),
  },
];

export const fallbackArtworks = [
  {
    id: 1,
    slug: "echoes-of-ancestry-no-3",
    title: "Echoes of Ancestry No. 3",
    artist: "Amina K. Bello",
    collectionSlug: "african-soul",
    story: "A warm, layered contemporary work inspired by African memory, earth pigment and modern interior quietness.",
    price: 1250000,
    refCode: "ART-AFR-001",
    image: "https://images.pexels.com/photos/34017793/pexels-photo-34017793.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    images: ["https://images.pexels.com/photos/34017793/pexels-photo-34017793.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"],
    sizeOptions: [
      { size: "Medium (60 × 90 cm)", price: 850000, dimensions: "60x90 cm" },
      { size: "Large (90 × 120 cm)", price: 1250000, dimensions: "90x120 cm" },
    ],
    orientation: "Portrait",
    editionType: "Limited Edition (1/25)",
    framingOptions: ["Obsidian Hardwood", "Terracotta Walnut", "Muted Gold Aluminum"],
    inStock: true,
    featured: true,
    watermarkEnabled: true,
    auctionEnabled: true,
    minBid: 1200000,
    bidIncrement: 100000,
    auctionEndTime: new Date(Date.now() + 7 * 86400000),
    auctionStatus: "active",
    currentHighestBid: 1600000,
    winnerEmail: null,
    createdAt: new Date(),
  },
  {
    id: 2,
    slug: "monolith-of-the-savannah",
    title: "Monolith of the Savannah",
    artist: "Kwame Osei",
    collectionSlug: "form",
    story: "A structural composition of shadow, stone and silence for contemporary homes and executive spaces.",
    price: 1850000,
    refCode: "ART-FRM-002",
    image: "https://images.pexels.com/photos/1582547/pexels-photo-1582547.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    images: ["https://images.pexels.com/photos/1582547/pexels-photo-1582547.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"],
    sizeOptions: [{ size: "Large (90 × 120 cm)", price: 1850000, dimensions: "90x120 cm" }],
    orientation: "Landscape",
    editionType: "Original Monotype",
    framingOptions: ["Obsidian Hardwood", "Terracotta Walnut"],
    inStock: true,
    featured: true,
    watermarkEnabled: true,
    auctionEnabled: false,
    minBid: 0,
    bidIncrement: 100000,
    auctionEndTime: null,
    auctionStatus: "none",
    currentHighestBid: 0,
    winnerEmail: null,
    createdAt: new Date(),
  },
  {
    id: 3,
    slug: "serengeti-at-dawn",
    title: "Serengeti at Dawn",
    artist: "Njabulo Dlamini",
    collectionSlug: "still",
    story: "A meditative landscape abstraction in ivory, stone and charcoal for calm refined spaces.",
    price: 980000,
    refCode: "ART-STL-003",
    image: "https://images.pexels.com/photos/8251476/pexels-photo-8251476.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    images: ["https://images.pexels.com/photos/8251476/pexels-photo-8251476.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"],
    sizeOptions: [{ size: "Medium (60 × 90 cm)", price: 980000, dimensions: "60x90 cm" }],
    orientation: "Landscape",
    editionType: "Limited Edition (1/50)",
    framingOptions: ["Muted Gold Aluminum", "Obsidian Hardwood"],
    inStock: true,
    featured: true,
    watermarkEnabled: true,
    auctionEnabled: false,
    minBid: 0,
    bidIncrement: 100000,
    auctionEndTime: null,
    auctionStatus: "none",
    currentHighestBid: 0,
    winnerEmail: null,
    createdAt: new Date(),
  },
];

export const fallbackArticles = [
  {
    id: 1,
    slug: "curating-contemporary-african-art-for-modern-luxury-interiors",
    title: "Curating Contemporary African Art for Modern Interiors",
    excerpt: "How thoughtful artwork gives homes and hospitality spaces a stronger emotional centre.",
    content: "Contemporary African art brings warmth, meaning and rhythm into modern interiors. ARTÉVO helps collectors choose pieces with scale, story and long-term presence.",
    author: "ARTÉVO Editorial",
    category: "Interior Styling",
    coverImage: "https://images.pexels.com/photos/10313987/pexels-photo-10313987.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    collectionSlug: "african-soul",
    published: true,
    readTime: "4 min read",
    createdAt: new Date(),
  },
];

export const fallbackSpaces = [
  {
    id: 1,
    spaceKey: "editions",
    title: "ARTÉVO Editions",
    subtitle: "Curated fine art prints for refined spaces",
    heroImage: "https://images.pexels.com/photos/10313987/pexels-photo-10313987.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    description: "Gallery-grade contemporary artwork for homes, offices and gifting.",
    features: [{ title: "Archival", desc: "Long-lasting museum-quality materials." }],
    caseStudies: [],
    ctaTitle: "Begin with ARTÉVO Editions",
    ctaText: "Choose a meaningful piece for your space.",
    updatedAt: new Date(),
  },
  {
    id: 2,
    spaceKey: "custom",
    title: "ARTÉVO Custom",
    subtitle: "Bespoke commissions from Ibadan",
    heroImage: "https://images.pexels.com/photos/29532559/pexels-photo-29532559.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    description: "Commission a piece tailored to your story, room and palette.",
    features: [{ title: "Bespoke", desc: "Created around your space and meaning." }],
    caseStudies: [],
    ctaTitle: "Commission Custom Artwork",
    ctaText: "Speak with our Ibadan studio.",
    updatedAt: new Date(),
  },
];

export const fallbackBankSettings = {
  id: 1,
  bankName: "Guaranty Trust Bank (GTBank) — Ibadan, Oyo State",
  accountName: "ARTÉVO NIGERIA LIMITED",
  accountNumber: "0192837465",
  sortCodeOrSwift: "GTBINGLA",
  currency: "Nigerian Naira (₦)",
  instructions: "Transfer the exact Naira amount and use your order reference as narration. For assistance WhatsApp 0903 019 2034.",
  contactEmail: "mobolajiolakunle8@gmail.com",
  updatedAt: new Date(),
};

export const fallbackOrders: any[] = [];
export const fallbackBids: any[] = [];
export const fallbackInquiries: any[] = [];
export const fallbackEvents: any[] = [];
export const fallbackSubscribers: any[] = [];
